### ISSUE TITLE
Require packages on install

### ISSUE THREAD

**Issue by bangingheads** [elliejs/Willump#1]
Willump requires packages that are not installed along with the pip install.

I had to manually install aiohttp and psutil into my venv.

Below is the successful pip freeze after installing these packages:

```
aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==20.3.0
chardet==4.0.0
idna==3.1
multidict==5.1.0
psutil==5.8.0
typing-extensions==3.7.4.3
willump==1.1.6
yarl==1.6.3
```

**Comment by elliejs** [comment]
Fixed in release 1.2.3 by moving from setup.cfg to setup.py
