### ISSUE TITLE
QUESTION - Its possible GET the rewards-track-items from the API?

### ISSUE THREAD

**Issue by Neinndall** [elliejs/Willump#13]
I was looking for a way to datamine the ITEMS of the events such as the worlds 2023, in the api it is called `/lol-event-shop/v1/reward-track-items` which should output the different levels with the corresponding items (tokens, emotes...) I don't know Whether this can be datamined ahead of time or can only be obtained when RIOT adds it.

**Comment by elliejs** [comment]
While an interesting question, this doesn't apply to the functioning of the library framework. Feel free to try mining.
