### ISSUE TITLE
i got 404 invaild function , what the problem is?

### ISSUE THREAD

**Issue by XilyFeAAAA** [elliejs/Willump#9]
when i use some of functions, such as '/lol-matchmaking/v1/ready-check/accept', i got 404 invaild function occasionally.It is strange that i can use it on an account, but when i use another account, i got 404 later.Is it about the cache?
![image](https://user-images.githubusercontent.com/114482179/215143576-6ddd530e-1b24-44a6-b416-638a76e06d8f.png)
![image](https://user-images.githubusercontent.com/114482179/215143597-2b793f0d-b2f5-44b5-b1dc-1df932da88bb.png)

**Comment by XilyFeAAAA** [comment]
I found that the problem is that these functions need http2, I tried to use httpx[http2=True], but there will be other problems, would http2 be added to willump ?

**Comment by elliejs** [comment]
This doesn't seem related to Willump and I'm closing it as such.
Willump does not have a self.doPost function, and what you've written there uses a different framework than the one already built in. Just try `wllp.request('post', '[uri_here]')`
